apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-eks
  namespace: cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cd
  template:
    metadata:
      labels:
        app: cd
    spec:
      containers:
        - name: cd
          image: 203754240973.dkr.ecr.us-east-1.amazonaws.com/ajkim-repository:jenkins
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: ecr2
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-eks-svc
  namespace: cd
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: cd
